// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RateMovie.Infraestructure.DataAccess;

#nullable disable

namespace RateMovie.Infraestructure.Migrations
{
    [DbContext(typeof(RateMovieDBContext))]
    [Migration("20250916170431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RateMovie.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(800)
                        .HasColumnType("varchar(800)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<sbyte>("Stars")
                        .HasColumnType("TINYINT");

                    b.HasKey("Id");

                    b.ToTable("Movies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Movies_Stars", "Stars BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Great performance by Heath Ledger, one of the best superhero movies.",
                            Name = "Batman: The Dark Knight",
                            Stars = (sbyte)5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Complex and intelligent film, requires the viewer's attention.",
                            Name = "Inception",
                            Stars = (sbyte)4
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Incredible visuals and a beautiful exploration of science fiction.",
                            Name = "Interstellar",
                            Stars = (sbyte)5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
