// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RateMovie.Infraestructure.DataAccess;

#nullable disable

namespace RateMovie.Infraestructure.Migrations
{
    [DbContext(typeof(RateMovieDBContext))]
    [Migration("20250917205534_MoreSeeds")]
    partial class MoreSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RateMovie.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(800)
                        .HasColumnType("varchar(800)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<sbyte>("Stars")
                        .HasColumnType("TINYINT");

                    b.HasKey("Id");

                    b.ToTable("Movies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Movies_Stars", "Stars BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Great performance by Heath Ledger, one of the best superhero movies.",
                            Name = "Batman: The Dark Knight",
                            Stars = (sbyte)5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Complex and intelligent film, requires the viewer's attention.",
                            Name = "Inception",
                            Stars = (sbyte)4
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Incredible visuals and a beautiful exploration of science fiction.",
                            Name = "Interstellar",
                            Stars = (sbyte)5
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Revolutionary sci-fi with a unique take on reality. Groundbreaking for its time.",
                            Name = "The Matrix",
                            Stars = (sbyte)5
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Classic mafia story, slow pacing but unmatched storytelling.",
                            Name = "The Godfather",
                            Stars = (sbyte)4
                        },
                        new
                        {
                            Id = 6,
                            Comment = "So bad it became a cult classic. Unintentionally hilarious.",
                            Name = "The Room",
                            Stars = (sbyte)1
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Epic conclusion to a decade of Marvel movies, lots of fan service.",
                            Name = "Avengers: Endgame",
                            Stars = (sbyte)4
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Emotional love story with spectacular visuals, though a bit too long.",
                            Name = "Titanic",
                            Stars = (sbyte)3
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Disturbing but brilliant character study, Joaquin Phoenix delivers a masterpiece.",
                            Name = "Joker",
                            Stars = (sbyte)5
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Funny, clever, and full of references. Works for both kids and adults.",
                            Name = "Shrek",
                            Stars = (sbyte)4
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Visually impressive but shallow story, feels repetitive.",
                            Name = "Transformers",
                            Stars = (sbyte)2
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Beautiful musical, strong performances, bittersweet ending.",
                            Name = "La La Land",
                            Stars = (sbyte)4
                        },
                        new
                        {
                            Id = 13,
                            Comment = "Uncanny visuals and lack of coherent plot. Painful to watch.",
                            Name = "Cats",
                            Stars = (sbyte)1
                        },
                        new
                        {
                            Id = 14,
                            Comment = "Chaotic story, weak villain, but some fun moments.",
                            Name = "Suicide Squad",
                            Stars = (sbyte)2
                        },
                        new
                        {
                            Id = 15,
                            Comment = "Disjointed narrative, inconsistent tone, feels rushed.",
                            Name = "Justice League (2017)",
                            Stars = (sbyte)2
                        },
                        new
                        {
                            Id = 16,
                            Comment = "Poor acting, terrible CGI. Fans deserved better.",
                            Name = "Mortal Kombat: Annihilation",
                            Stars = (sbyte)1
                        },
                        new
                        {
                            Id = 17,
                            Comment = "Total disrespect to the source material, universally hated.",
                            Name = "Dragonball Evolution",
                            Stars = (sbyte)1
                        },
                        new
                        {
                            Id = 18,
                            Comment = "Decent action, but uneven tone. Carried by Tom Hardy.",
                            Name = "Venom",
                            Stars = (sbyte)3
                        },
                        new
                        {
                            Id = 19,
                            Comment = "Some good visuals, but overcrowded plot and wasted villains.",
                            Name = "The Amazing Spider-Man 2",
                            Stars = (sbyte)3
                        },
                        new
                        {
                            Id = 20,
                            Comment = "Charming moments, but franchise fatigue shows.",
                            Name = "Pirates of the Caribbean: On Stranger Tides",
                            Stars = (sbyte)3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
